.PHONY: build build-all docker-build docker-all-in-one clean test fmt

BIN_DIR ?= bin
GO ?= go

# ── Build (Docker — no host Go required) ──────────────────────
build:
	@mkdir -p $(BIN_DIR)
	DOCKER_BUILDKIT=1 sudo docker build -f deploy/docker/Dockerfile --target export --output type=local,dest=$(BIN_DIR) .

build-all:
	@mkdir -p $(BIN_DIR)
	DOCKER_BUILDKIT=1 sudo docker build -f deploy/docker/Dockerfile.all-in-one --target export --output type=local,dest=$(BIN_DIR) .

# ── Docker ─────────────────────────────────────────────────────
docker-build:
	DOCKER_BUILDKIT=1 sudo docker build -t flowgent:latest -f deploy/docker/Dockerfile .

docker-all-in-one:
	DOCKER_BUILDKIT=1 sudo docker build -t flowgent:all-in-one -f deploy/docker/Dockerfile.all-in-one .

# ── Utilities ──────────────────────────────────────────────────
clean:
	rm -rf $(BIN_DIR)/

test:
	cd src/common && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/model && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/messaging && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/cache && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/config && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/wallet && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/notifier && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/api && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/store && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/sandbox && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/core && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/cmd && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...

fmt:
	cd src/common && $(GO) fmt ./...
	cd src/model && $(GO) fmt ./...
	cd src/messaging && $(GO) fmt ./...
	cd src/cache && $(GO) fmt ./...
	cd src/config && $(GO) fmt ./...
	cd src/wallet && $(GO) fmt ./...
	cd src/notifier && $(GO) fmt ./...
	cd src/api && $(GO) fmt ./...
	cd src/store && $(GO) fmt ./...
	cd src/sandbox && $(GO) fmt ./...
	cd src/core && $(GO) fmt ./...
	cd src/cmd && $(GO) fmt ./...
