.PHONY: build build-flowgent examples example-mcps clean test fmt

GO ?= go

# ── Default ────────────────────────────────────────────────
build: build-flowgent

# ── Binaries ───────────────────────────────────────────────
build-flowgent:
	CGO_ENABLED=0 $(GO) build -C src/cmd -o ../../bin/flowgent \
		-ldflags "-X main.Version=dev -X main.GitCommit=$(shell git rev-parse HEAD) -X main.BuildTime=$(shell date -u +%Y-%m-%dT%H:%M:%SZ)" \
		./src/flowgent

# ── Example MCPs ───────────────────────────────────────────
example-mcps: example-mcp-github example-mcp-sonarqube example-mcp-sonatypeiq example-mcp-nexus3

example-mcp-github:
	cd examples/mcp-github && CGO_ENABLED=0 $(GO) build -o ../../bin/github-mcp .

example-mcp-sonarqube:
	cd examples/mcp-sonarqube && CGO_ENABLED=0 $(GO) build -o ../../bin/sonarqube-mcp .

example-mcp-sonatypeiq:
	cd examples/mcp-sonatypeiq && CGO_ENABLED=0 $(GO) build -o ../../bin/sonatype-iq-mcp .

example-mcp-nexus3:
	cd examples/mcp-nexus3 && CGO_ENABLED=0 $(GO) build -o ../../bin/sonatype-nexus3-mcp .

examples: example-mcps

# ── Utilities ──────────────────────────────────────────────
clean:
	rm -rf bin/

test:
	cd src/common && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/model && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/messaging && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/cache && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/config && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/wallet && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/notifier && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/api && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/store && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/sandbox && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/core && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...
	cd src/cmd && CGO_ENABLED=0 $(GO) test -count=1 -timeout 120s ./...

GO ?= go
fmt:
	cd src/common && $(GO) fmt ./...
	cd src/model && $(GO) fmt ./...
	cd src/messaging && $(GO) fmt ./...
	cd src/cache && $(GO) fmt ./...
	cd src/config && $(GO) fmt ./...
	cd src/wallet && $(GO) fmt ./...
	cd src/notifier && $(GO) fmt ./...
	cd src/api && $(GO) fmt ./...
	cd src/store && $(GO) fmt ./...
	cd src/sandbox && $(GO) fmt ./...
	cd src/core && $(GO) fmt ./...
	cd src/cmd && $(GO) fmt ./...

# ── Docker ─────────────────────────────────────────────────
docker-build:
	docker build -t flowgent/flowgent:latest .
