INSERT OR IGNORE INTO iam_namespace (id, name, labels, description, namespace_id, status, created_at, created_by, updated_at, updated_by, del_flag)
VALUES ('default', 'Default', '{}', 'Default Flowgent organization/team boundary', 'default', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0);

INSERT OR REPLACE INTO iam_role (id, name, builtin, permissions, description, namespace_id, status, created_at, created_by, updated_at, updated_by, del_flag)
VALUES
 ('builtin-platform-owner', 'platform-owner', 1, '["*"]', 'Deployment break-glass and platform administration', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-namespace-owner', 'owner', 1, '["namespace.*","agent.*","skill.*","flow.*","flow_release.*","llm_provider.*","mcp.*","notification.*","knowledge.*","run.*","approval.*","trace.*","iam.*","service_account.*"]', 'Full ownership of one namespace', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-flow-owner', 'flow-owner', 1, '["flow.*","run.*","task.read","approval.*","trace.read","flow_release.*"]', 'Full administration of one exact Flow and its execution evidence', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-maintainer', 'maintainer', 1, '["namespace.read","agent.*","skill.*","flow.*","flow_release.*","llm_provider.read","llm_provider.use","mcp.read","mcp.use","notification.read","knowledge.*","run.*","approval.*","trace.read"]', 'Maintain resources and operations without secret or membership administration', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-writer', 'writer', 1, '["namespace.read","agent.read","agent.use","agent.write","skill.read","skill.use","skill.write","flow.read","flow.use","flow.write","flow_release.read","flow_release.install","llm_provider.read","llm_provider.use","mcp.read","mcp.use","notification.read","knowledge.read","knowledge.write","run.read","run.trigger","run.cancel","approval.read","trace.read"]', 'Author resources and trigger runs', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-operator', 'operator', 1, '["namespace.read","agent.read","agent.use","skill.read","skill.use","flow.read","flow.use","flow_release.read","flow_release.install","llm_provider.read","llm_provider.use","mcp.read","mcp.use","notification.read","run.read","run.trigger","run.cancel","approval.read","approval.resolve","trace.read"]', 'Operate approved flows without modifying definitions', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-reader', 'reader', 1, '["namespace.read","agent.read","skill.read","flow.read","flow_release.read","llm_provider.read","mcp.read","notification.read","knowledge.read","run.read","approval.read","trace.read"]', 'Read non-secret namespace resources and execution evidence', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-secret-manager', 'secret-manager', 1, '["namespace.read","llm_provider.read","llm_provider.secret.manage","mcp.read","mcp.secret.manage","notification.read","notification.secret.manage"]', 'Manage write-only integration secrets', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-auditor', 'auditor', 1, '["namespace.read","run.read","approval.read","trace.read","iam.audit.read"]', 'Read execution and immutable security audit evidence', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-system-controller', 'system-controller', 1, '["flow.read","run.read","run.internal.create","namespace.runtime.manage"]', 'Controller workload permissions', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-system-jobmanager', 'system-jobmanager', 1, '["flow.read","agent.read","agent.use","skill.read","skill.use","llm_provider.read","llm_provider.use","mcp.read","mcp.use","run.read","run.internal.update","task.read","task.internal.write","approval.internal.create","notification.emit"]', 'JobManager workload permissions', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-system-taskmanager', 'system-taskmanager', 1, '["agent.read","agent.use","skill.read","skill.use","llm_provider.read","llm_provider.use","mcp.read","mcp.use","run.read","task.read","task.internal.write","approval.internal.create","notification.emit"]', 'TaskManager workload permissions', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-system-notifier', 'system-notifier', 1, '["notification.read","notification.internal.deliver","approval.platform.read"]', 'Notifier workload permissions', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-system-a2a', 'system-a2a', 1, '["flow.read","flow.use","run.read","run.trigger","run.cancel","approval.read","approval.resolve","trace.read"]', 'A2A gateway workload permissions', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('builtin-system-allinone', 'system-allinone', 1, '["flow.read","flow.use","run.read","run.trigger","run.cancel","run.internal.create","run.internal.update","agent.read","agent.use","skill.read","skill.use","llm_provider.read","llm_provider.use","mcp.read","mcp.use","task.read","task.internal.write","approval.read","approval.resolve","approval.internal.create","approval.platform.read","notification.read","notification.emit","notification.internal.deliver","trace.read","namespace.runtime.manage"]', 'In-process development runtime permissions', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0);

INSERT OR REPLACE INTO iam_principal (id, type, issuer, external_id, username, display_name, email, attributes, description, namespace_id, status, created_at, created_by, updated_at, updated_by, del_flag)
VALUES
 ('breakglass:root', 'user', 'flowgent:breakglass', 'root', 'breakglass-root', 'Flowgent break-glass administrator', '', '{}', 'Rotatable deployment emergency identity', '', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('service:controller', 'service_account', 'flowgent:internal', 'controller', 'controller', 'Flowgent Controller', '', '{}', 'Internal workload identity', '', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('service:jobmanager', 'service_account', 'flowgent:internal', 'jobmanager', 'jobmanager', 'Flowgent JobManager', '', '{}', 'Internal workload identity', '', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('service:taskmanager', 'service_account', 'flowgent:internal', 'taskmanager', 'taskmanager', 'Flowgent TaskManager', '', '{}', 'Internal workload identity', '', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('service:notifier', 'service_account', 'flowgent:internal', 'notifier', 'notifier', 'Flowgent Notifier', '', '{}', 'Internal workload identity', '', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('service:a2a', 'service_account', 'flowgent:internal', 'a2a', 'a2a', 'Flowgent A2A Gateway', '', '{}', 'Internal workload identity', '', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('service:allinone', 'service_account', 'flowgent:internal', 'allinone', 'allinone', 'Flowgent All-in-One Runtime', '', '{}', 'Ephemeral in-process development identity', '', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0);

INSERT OR REPLACE INTO iam_role_binding (id, role_id, subject_type, subject_id, resource_type, resource_id, effect, conditions, expires_at, description, namespace_id, status, created_at, created_by, updated_at, updated_by, del_flag)
VALUES
 ('binding-breakglass-root', 'builtin-platform-owner', 'user', 'breakglass:root', 'platform', '*', 'ALLOW', '{}', NULL, 'Deployment break-glass owner', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('binding-system-controller', 'builtin-system-controller', 'service_account', 'service:controller', 'platform', '*', 'ALLOW', '{}', NULL, 'Controller workload grant', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('binding-system-jobmanager', 'builtin-system-jobmanager', 'service_account', 'service:jobmanager', 'platform', '*', 'ALLOW', '{}', NULL, 'JobManager workload grant', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('binding-system-taskmanager', 'builtin-system-taskmanager', 'service_account', 'service:taskmanager', 'platform', '*', 'ALLOW', '{}', NULL, 'TaskManager workload grant', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('binding-system-notifier', 'builtin-system-notifier', 'service_account', 'service:notifier', 'platform', '*', 'ALLOW', '{}', NULL, 'Notifier workload grant', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('binding-system-a2a', 'builtin-system-a2a', 'service_account', 'service:a2a', 'platform', '*', 'ALLOW', '{}', NULL, 'A2A workload grant', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0),
 ('binding-system-allinone', 'builtin-system-allinone', 'service_account', 'service:allinone', 'platform', '*', 'ALLOW', '{}', NULL, 'All-in-one runtime grant', '*', 'ACTIVE', datetime('now'), 'system', datetime('now'), 'system', 0);
