{{- if eq .Values.global.mode "session" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowgent.fullname" . }}-jobmanager
  labels:
    {{- include "flowgent.labels" . | nindent 4 }}
    app.kubernetes.io/component: jobmanager
spec:
  replicas: {{ .Values.jobmanager.replicas }}
  selector:
    matchLabels:
      {{- include "flowgent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: jobmanager
  template:
    metadata:
      labels:
        {{- include "flowgent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["/app/flowgent"]
          args: ["jobmanager", "start", "-c", "/etc/flowgent/flowgent.yaml"]
          env:
            {{- include "flowgent.internalEnv" . | nindent 12 }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FLOWGENT__TM__DEPLOY
              value: {{ include "flowgent.fullname" . }}-taskmanager
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- include "flowgent.extraSecretEnv" . | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/flowgent
          resources:
            {{- toYaml .Values.jobmanager.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "flowgent.fullname" . }}-config
{{- end }}
