{{- if .Values.application.enabled }}
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgent.fullname" . }}-postgresql
  labels:
    {{- include "flowgent.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app.kubernetes.io/component: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowgent.fullname" . }}-postgresql
  labels:
    {{- include "flowgent.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: registry.cn-shenzhen.aliyuncs.com/wl4g/bitnami_postgresql:18.3
          env:
            - name: POSTGRESQL_USERNAME
              value: "flowgent"
            - name: POSTGRESQL_PASSWORD
              value: "flowgent"
            - name: POSTGRESQL_DATABASE
              value: "flowgent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
      volumes:
        - name: data
          emptyDir: {}
{{- end }}
{{- end }}
