scan_servers:
  
  scanner:
    type: mixed
    servers:
      sonarqube:
        base_url: "http://localhost:9000"
        api_token: "squ_38a0d0223a67b10f9eade37e84c468085323349a"
        projects:
          - key: "rengine"
            name: "Rengine"
          - key: "cyberbot"
            name: "CyberBot"
        scanner_cli: "/opt/sonar-scanner/bin/sonar-scanner"
        healthcheck: "http://localhost:9000/api/system/status"
        
      sonatype-iq:
        base_url: "http://localhost:8070"
        admin_url: "http://localhost:8071"  
        username: "admin"
        password: "admin123"
        application_id: "rengine"
        healthcheck: "http://localhost:8070/"

projects:
  - name: "rengine"
    repo: "github.com/wl4g/rengine"
    source: "/root/rengine"
    build_command: "mvn -B clean compile -DskipTests"
    scans: ["sonarqube"]
    
  - name: "cyberbot"
    repo: "local"
    source: "/root/cyberbot"  
    build_command: "make build"
    scans: ["sonarqube"]
